"""empty message

Revision ID: efe170d36a6a
Revises: 
Create Date: 2024-08-14 00:25:44.266331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efe170d36a6a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bebris_playlists',
    sa.Column('playlist_name', sa.String(), nullable=False),
    sa.Column('playlist_color', sa.String(), nullable=False),
    sa.Column('emoji', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('playlist_color'),
    sa.UniqueConstraint('playlist_name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('user_name', sa.Text(), nullable=True),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('second_name', sa.Text(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'MODERATOR', 'ADMINISTRATOR', name='role'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('bebris_lessons',
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('lesson_title', sa.String(), nullable=False),
    sa.Column('lesson_nubmer', sa.String(), nullable=False),
    sa.Column('video_nubmer', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['bebris_playlists.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_title')
    )
    op.create_table('bebris_flash_cards',
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('front_side', sa.String(), nullable=False),
    sa.Column('back_side', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['bebris_lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bebris_lesson_statistics',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('correct_answers', sa.Integer(), nullable=False),
    sa.Column('wrong_answers', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['bebris_lessons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bebris_flash_card_statistics',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('flashcard_id', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['flashcard_id'], ['bebris_flash_cards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bebris_flash_card_statistics')
    op.drop_table('bebris_lesson_statistics')
    op.drop_table('bebris_flash_cards')
    op.drop_table('bebris_lessons')
    op.drop_table('users')
    op.drop_table('bebris_playlists')
    # ### end Alembic commands ###
